root = "."
tmp_dir = "tmp"

[build]
  # Build from the delivery directory
  cmd = "go build -o ./tmp/main ./delivery"
  bin = "./tmp/main"
  
  # Watch these extensions
  include_ext = ["go", "html", "tpl"]
  
  # Exclude unnecessary directories
  exclude_dir = ["tmp", "vendor", ".git"]
  
  # Optional: Delay before restarting (milliseconds)
  delay = 1000

[log]
  time = false  # Disable timestamps in logs