
name: lazyme

services:
  # mongo:
  #   image: mongo:6
  #   container_name: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lazyme
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"


volumes:
  mongo_data: