
name: lazyme

services:
  redis:
    image: redis:latest 
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lazyme
    depends_on:
      - redis
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  redis_data: