
name: lazyme

services:
  redis:
    image: redis:latest 
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: lazymepass0011
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lazyme
    depends_on:
      - redis
      - mongodb
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  redis_data:
  mongo_data: